### ISSUE TITLE
Shipping hs-booster-proxy

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/hs-backend-booster#172]
- [X] we need to rename the tools (hs-booster-proxy ===> booster, hs-backend-booster ===> booster-dev)

## Consolidate and facilitate booster usage in evm-semantics
- [ ] write an instruction of how to add a repository to kup
- [X] `kup install booster`. In order to keep it private, kup install kevm will not install the booster, the user should manually install the booster and the command below will look for your installation of the booster on the path
- [x] Issues with the LLVM compilation (blockchain-plugin, see https://github.com/runtimeverification/blockchain-k-plugin/issues/152)
- [x] Set up CI to test with booster (at least a minimal smoke-test) https://github.com/runtimeverification/evm-semantics/pull/1890

## Standardise kevm compile outputs:
- [x] `kevm foundry-{kompile,prove} --use-booster` which automates what we did with `kore-rpc-command` before https://github.com/runtimeverification/evm-semantics/pull/1890
- [ ] general `kevm kompile/prove --use-booster` will need a standardised output format like foundry uses; i.e. `--use-booster` expects an interpreter at `<project_dir>/kompiled-llvm/interpreter.{so,dylib}`

**Comment by jberthold** [comment]
Post-poning the last point of `general kevm kompile/prove --use-booster will need a standardised output format`
to a new ticket (since it requires a lot of downstream coordination).
