### ISSUE TITLE
Open sourcing plan for booster backend

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/hs-backend-booster#180]
Once we have the booster tested on KEVM and passing all the same tests (see https://github.com/runtimeverification/hs-backend-booster/issues/172), and we have confidence in it's efficacy, we want to begin open sourcing most of the codebase, but in a way that allows us to keep some performance benefits closed source. There are three key things that we can keep closed source which realize better performance, while open-sourcing the majority of the core algorithm.

- Parallelism. This will be handled by pyk library instead of haskell backend.
- Rule indexing. We can ship a worse rule indexer in the open source variant (or a rule indexer that always returns `*`).
- Unification. We can ship a less powerful unification (for example, without handling any AC unification), but plugin a more powerful unfication that allows less fallback to original codebase for closed source variant.

The goals of open sourcing the booster codebase are:

- Reduce maintenance burden. We can delete parts of the old codebase that the new booster backend is able to handle directly, and won't have to have changes into two separate places for every API change to the RPC protocol.
- Better performance/first-touch experience for new users.
- Make it easy to keep some performance advantage for our servers only (in KaaS setting, for example).

To accomplish this, one idea is:

- Make the booster accept the rule unification and rule indexing algorithms to use as an input.
- Copy the code which implements the booster symbolic execution into the old backend (and all the needed datastructures), but instead do:
  - Rule indexing which always returns `*`
  - Unification which does not attempt to handle AC symbols at all.
- Change the old backend to have an extra flag `--booster`, which enables the booster backend (with the worse rule indexing and unification algorithms) to go first, then fallback to the old backend.
- Get tests passing with this variant on KEVM.
- Make sure that tests are passing with the more advanced rule indexing and unification plugged in as well.

One thing I'm not sure about is if this actually reduces our maintenance burden (which would be a core goal here).

Another approach would be to replace components of the old backend wholesale. For example, we could replace the entire simplifacation algorithm of the old backend at once with the new equation simplifier. This would require that we reach feature parity though.

Thougths?

**Comment by jberthold** [comment]
Closing this as booster is now open-source
