### ISSUE TITLE
Upgrade and automate upgrading of K version for booster integration tests

### ISSUE THREAD

**Issue by jberthold** [runtimeverification/hs-backend-booster#246]
https://github.com/runtimeverification/hs-backend-booster/blob/main/flake.nix#L5

**Comment by goodlyrottenapple** [comment]
Currently blocked on updating to latest version of K. THis should be unblocked once #264 is merged

**Comment by jberthold** [comment]
Decided to not automate the K version upgrade (too much traffic). Maybe a cron job could be set up but we can do it manually.
