### ISSUE TITLE
Matching on K/KItem sort injections

### ISSUE THREAD

**Issue by goodlyrottenapple** [runtimeverification/hs-backend-booster#254]
@dwightguth has pointed out a case when a function should not be applied, but the booster does apply the owise case. Namely:

given

```
syntax Bool ::= isInt(K) [function]
rule isInt(I:Int) => true
rule isInt(_) => false [owise]
```

and a configuration with `isInt(X:KItem)`, the booster rewrites this term into `false`. Here is the simp trace for the application of this function:

```
isInt(VarX:SortKItem{})
Symbols differ:
kseq(Eq#VarInt:SortInt{}, dotk())
VarX:SortKItem{} @(hs-backend-booster-0.0.0-inplace:Booster.Pattern.ApplyEquations library/Booster/Pattern/ApplyEquations.hs:488:5)
[Simplify] Simplifying term
isInt(VarX:SortKItem{})
to
"false"
```

The issue above is the special treatment of injections into K, namely if we look at the kore definition of `isInt` and its internalisation, we get these two equations:

```
isInt(kseq{}(inj{SortInt{}, SortKItem{}}(Var'Unds'Gen1:SortInt{}),dotk{}())) = \dv{SortBool{}}("true")
isInt(VarK:SortK{})                                                          = \dv{SortBool{}}("false")
```

This is problematic because when applying the equations to the term `isInt(inj{SortKItem{}, SortK{})(VarX:SortKItem{}))`, the match between `kseq{}(..)` and `VarX:SortKItem{}` obviously fails... Not sure if this is an issue with how pyk generates kore for the K term `isInt(X:KItem)` (possibly related to https://github.com/runtimeverification/pyk/issues/565, i have not tested with a new enough version of pyk which contains the fix for this) or if the booster is supposed to handle the `kseq(..., dotk{})` patterns as a special case when matching...

**Comment by dwightguth** [comment]
kseq and dotk are just regular constructors. What is supposed to happen, if I understand correctly, is that the first rule doesn't apply because pattern matching fails, but the second rule also doesn't apply because unification of the pattern with the first rule succeeds nontrivially.

**Comment by goodlyrottenapple** [comment]
I would assume that the booster should determine that the match between the first pattern `isInt(I:Int)` and `isInt(X:KItem)` is indeterminate because `KItem` is a super-sort of `Int` and could therefore apply. Then, because the first equation is indeterminate, no other equations should be attempted to be matched and we should abort.

Is this intuition correct?

**Comment by dwightguth** [comment]
I mean, it ought  to be safe to apply any rules that have the same priority; but no rules of lower priority should apply.

**Comment by jberthold** [comment]
Reading through this issue description and the slack discussion, I noticed that we should also clarify whether/why `isInt(inj{SortKItem{}, SortK{}}(...)` would be accepted in the booster, given that `SortKItem` is _not_ a subsort of `SortK`.

The syntax for `isInt`  stipulates an argument of sort `K` but the rules in K are formulated with arguments of other sorts.
From what @goodlyrottenapple writes, the compilation translates those by wrapping them into `kseq`. 
* What happens if we use input term `kseq(X:SortKItem{}, dotk: SortK{})`?
* Are incorrect injections (non-subsort injections) detected by booster when internalising input?
