### ISSUE TITLE
Simplify side conditions  while applying rules

### ISSUE THREAD

**Issue by jberthold** [runtimeverification/hs-backend-booster#255]
As #243 turns out to be a major issue for real-world proofs, the booster backend should be extended to apply equation-based simplification (on symbolic terms) to conditions of rewrite rules.
Currently, conditions are only checked when they are fully concrete (i.e., they do not contain any variables) and booster aborts  rewriting if a rule condition cannot be determined. When applying function equations and a condition cannot be determined, evaluation stops (no further equations are attempted). When applying simplification equations, indeterminate conditions lead to skipping the equation in question.

- [X] Use simplification while checking symbolic conditions on rewrite rules. This was introduced together with #227 
- [x] Attempt to evaluate/simplify symbolic conditions on equations. This extension to the evaluator introduces recursive evaluation and needs to be protected against looping, the implementation is complex. It may also cause performance regressions.
- [x] For both cases, any indeterminate simplified conditions that are _ensured_ should be returned instead of the original ones

This work stream is an initial exploration of the potential of this change, a second iteration should follow whose design is informed by the initial findings.

**Comment by ehildenb** [comment]
Keep in mind that #243 is resolved now, because we have `--simplify-after-exec` flag. So we should not focus on this unless it is actually the next 80% thing to focus on (which requires measuring all the fallback cases).

**Comment by jberthold** [comment]
Re-opening this because #265 had to revert the implementation, pending investigation

**Comment by palinatolmach** [comment]
@geo2a do you think there're any updates for this issue? Thanks!

**Comment by yale-vinson** [comment]
@geo2a, @jberthold Do either of you have an update for this issue? [#271](https://github.com/runtimeverification/hs-backend-booster/issues/271) is still open, but [#265](https://github.com/runtimeverification/hs-backend-booster/pull/265) shows as merged. Is this still blocked, or can we move forward with this?

**Comment by jberthold** [comment]
#265 is actually a _revert_ of the first version of recursive constraint evaluation. The recursion caused issues with a larger proof that suddenly ran much slower than before.

My update is, we re-implemented recursive constraint evaluation but it caused a slight slowdown in some of the `foundry` and `kevm` testing proofs so we haven't merged it yet.
We merged a change that introduces a cache for prior simplifications, which should hopefully address/alleviate the problem that caused us to revert the original implementation.

The first step is probably to re-check the original problem reported in #243  since symbolic side conditions are now indeed simplified, just not recursively.

**Comment by jberthold** [comment]
This appears to have been solved by changes to the  post-exec simplification (reinstated recently), closing the original issue for now. If there is a specific issue with simplifications not being applied we will open a new ticket.
