### ISSUE TITLE
add-module should allow the same module multiple times 

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/hs-backend-booster#267]
This is the same issue as runtimeverification/haskell-backend#3640, however, it needs to be implemented in both backends.

**Comment by goodlyrottenapple** [comment]
This can be enabled by simply removing this check:

https://github.com/runtimeverification/hs-backend-booster/blob/046286b5d22d795ceb2fa5e499f8196aa9aa50ab/library/Booster/Syntax/ParsedKore/Internalise.hs#L95-L96

However, not sure if we also want to check that this module matches a previously added one? Removing the above will just override the previous module of the same name, as far as I can tell?

**Comment by goodlyrottenapple** [comment]
implemented by #270
