### ISSUE TITLE
Produce a structured log of pre- and  post-states when Booster aborts and falls back to Kore

### ISSUE THREAD

**Issue by geo2a** [runtimeverification/hs-backend-booster#295]
Kontrol proofs often cause `kore-rpc-booster` to abort in Booster and fall-back to Kore several times during an `execute` request. More and more abort cases require deep analysis to determine what exactly caused the abort. @ehildenb suggest implementing a tool to extract focused K claims (which need only a few rewrite steps to be proved) from large Kontrol integrations with `kore-rpc-booster`. While the tool itself will be implemented at `kontrol`/`pyk` level, `kore-rpc-booster` needs to provide data for it.

## Data that we need to produce 

What we want to know is:
* the pre-state, i.e. the one lead to Booster aborting;
* the post-state, i.e. the one Kore gave us back after executing for one step.

## How to produce that data

We want the two states to be ready-for-consumption by `pyk` , so we need to externalize them to KoreJson. Modifying the response data to make them available along with rewriting and simplification logs seems too heavy-weight (these logs seem to not be used at that point anyway...) Therefore I suggest logging them at a custom `BoosterAbort` log-level into `stderr` or a provided file. This way we would be able to have the following flow:

```
$ kore-rpc-booster definition.kore --llvm-backend-library interpreter.so -l Abort > file.out &
$ rpc-client send request.json
$ # filter file.out for BoosterAbort JSON messages
$ kevm generate-claim file.out
```

**Comment by goodlyrottenapple** [comment]
@geo2a bear in mind that the log will contain other log messages, not just the abort ones

**Comment by ehildenb** [comment]
Is it possible for the logs returned to be structured so we can filter on the pyk side for just those terms in the pre/post abort states? Then pyk can handle turning them into pretty-printed claims itself, no problem.

**Comment by geo2a** [comment]
@goodlyrottenapple I though we could introduce a specific log-level for this and only turn this one on? 

Alternatively, we can consider using the eventlog custom user even tracing infrastructure. It actually seems more appropriate. If the messages are too long for the GHC eventlog, we can trace them into a file.

@ehildenb either way, we definitely could output structured data.

**Comment by goodlyrottenapple** [comment]
Currently we log at the default level plus whatever `-l {Rewrite,Simplify}` we specify

**Comment by goodlyrottenapple** [comment]
Also, not sure why we need another logging format when we already have structured traces from rpc responses: https://github.com/runtimeverification/hs-backend-booster/blob/b840b40b9190e17e7d858985cfa149e43d953b48/library/Booster/JsonRpc.hs#L345-L415

**Comment by ehildenb** [comment]
Yeah, I'd propose just adding it to the current logging infrastructure for sure, that would be ideal if we could get it back per RPC request. Would be awesome if we could pass in on the RPC request that we want this information logged as well.

**Comment by geo2a** [comment]
**Update**: we've identified and fixed several places where rewriting logs were not returned correctly (#302 , now merged). The next step is to (1) modify `kore-rpc-types` to allows logging terms which caused the abort in Booster and (2) modify `kore` to log the successfully rewritten state. I've opened an issue in `haskell-backend` to keep track of that: https://github.com/runtimeverification/haskell-backend/issues/3654
