### ISSUE TITLE
Booster aborts in a Kontrol poof, requiring better Map-matching

### ISSUE THREAD

**Issue by geo2a** [runtimeverification/hs-backend-booster#298]
@PetarMax has shared a bug report (Slack [link](https://runtimeverification.slack.com/files/U03FQGFBLBW/F05R8N80404/bug_report.tar.gz)) that exhibits Booster falls back to Kore. We need to investigate the reason for these fall-backs.

**Comment by jberthold** [comment]
From running all `execute` requests in the linked tarball :+1: 
|   Abort reason | Count | Time range for fall-back |
|----------------- | -------- | ----------------------------------- |
| a condition in rule EVM.jumpi.true   | 27 | [15.43 .. 25.06 .. 36.98] |
| a condition in rule /evm.md: 1319  | 18 | [27.45 .. 31.46 .. 35.29] |
| unification of rule /evm.md: 1185  | 16 | [17.76 .. 30.77 .. 36.9] |
| unification of rule /evm.md: 1195  | 4  | [30.58 .. 33.72 .. 36.25] |
| unification of rule /evm.md: 1947  | 4  | [30.77 .. 33.82 .. 36.5] |
| unification of rule /evm.md: 2162  | 4  | [17.51 .. 23.13 .. 28.97] |
| definedness of rule /evm.md: 1317  | 3  | [3.15 .. 7.85 .. 17.24] |
| unification of rule /evm.md: 1220  | 2  | [17.58 .. 23.46 .. 29.34] |
| unification of rule /evm.md: 1246  | 2  | [17.47 .. 23.05 .. 28.63] |
| unification of rule /evm.md: 789  | 2  | [17.92 .. 24.72 .. 31.52] |
| a condition in rule /evm.md: 1096  | 1  | [35.22 .. 35.22 .. 35.22] |
| unification of rule /evm.md: 1141  | 1  | [28.53 .. 28.53 .. 28.53] |

* The 27 abourts on `jumpi` conditions display a variety of conditions, some very simple but with variables, others where a (recursive) simplification of the condition might have produced a usable decision.
* Rule `evm.md: 1319` is an update of a map, the condition is `notBool ACCT in_keys(TS:Map)`  . The `TS` map has variables in the _values_ but not in the keys. The `Rewrite` log level displays the map contents (which contained the `ACCT` key), it might have been possible to evaluate the call to `in_keys` (**to investigate**)
* Rule `evm.md: 1185` is a map lookup in the `accounts` map using a key from the `id` cell. The `Rewrite` log level displays the account map contents, and the `id` field is indeed one of the keys. **Maybe the unification should apply the already-obtained substitution to the work queue earlier.**
* Rule `evm.md: 1195` is a write access to a map cell whose key is again from the `id` field. This is the same case as above.
* Rule `evm.md: 1947` (`#gasExec`) likewise tries to look up an account in the `accounts` map  by the ID in the `id` field.
* Rule `evm.md: 2162` (`#accountNonexistent(ACCT)`) does a comparable lookup, but this time `ACCT` comes from the `k` cell (would expect this to work, as we have examples of such map lookups).
* Rule `evm.md: 1317` contains a map update on the RHS, but should be defined (updates an existing association in the map).

Also remarkable: each of these fall-backs takes considerable time (often >23sec).

**Comment by geo2a** [comment]
Closed by https://github.com/runtimeverification/hs-backend-booster/pull/360
