### ISSUE TITLE
Single element `Map` update for a defined key in a cell map

### ISSUE THREAD

**Issue by geo2a** [runtimeverification/hs-backend-booster#318]
@virgil-serbanuta reports that Booster often aborts in [Elrond semantics](https://github.com/runtimeverification/elrond-semantics):
```
[Rewrite] Uncertain about definedness of rule  ELROND-CONFIG.transferFundsH because of: non-total symbol Lbl_AccountCellMap_ non-total symbol LblAccountCellMapItem @(hs-backend-booster-0.0.0-DpKnlYxxzPeBfB7OJwCE7f:Booster.Pattern.Rewrite library/Booster/Pattern/Rewrite.hs:559:18)
```

Virgil supposes that using a plain `Map` instead of a cell-map here should not abort, because the former supports `MyMap => MyMap[key <- value]`, but I'm actually not sure. Things to check:
* the resulting Kore for both cell-map and Map rules
* Booster internalization of both rules

We need to determine what exactly happens and find out if we could extend the rewriting code to update the map in definedness-preserving way to avoid an abort here.

Note: the meaning of this rule is updating some metadata for an account address. The address is likely to be concrete.

Slack discussion: https://runtimeverification.slack.com/archives/CC360GUTG/p1695763717209189

**Comment by geo2a** [comment]
Seems related: https://github.com/runtimeverification/hs-backend-booster/issues/298

**Comment by jberthold** [comment]
Noting while we look at this:
* `LblAccountCellMapItem` should probably be a total function?
* Independently, the update function on normal maps (not cell maps) seems to be less problematic (it has an `upsert` semantics so the resulting map should be defined in any case, whether or not the key pre-existed).
   It should be investigated how cell map updates get desugared.

**Comment by ehildenb** [comment]
Would likely be modification here: https://github.com/runtimeverification/evm-semantics/pull/2152

**Comment by ehildenb** [comment]
Indeed, normal `MapItem` is also total: https://github.com/runtimeverification/k/blob/master/k-distribution/include/kframework/builtin/domains.md#map-elements
