### ISSUE TITLE
Old Haskell backend is built twice by K Maven build

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/hs-backend-booster#346]
After running `mvn clean` in a K repository at commit `b1fcdbc83fa7d91db23741a128f67dba4e951794`, I noticed that `mvn package -DskipTests` built the old Haskell backend _twice_ - presumably, once as its own component, and once as a dependency of the booster.

This might somehow be an issue with the way that Stack et. al. are configured on my machine; if it isn't we should try and resolve this so the old backend only gets built once. A full Maven build log is attached:
[maven.txt](https://github.com/runtimeverification/hs-backend-booster/files/13113110/maven.txt)

**Comment by Baltoli** [comment]
Note that I see this happening in CI as well as locally on my own machine.

**Comment by goodlyrottenapple** [comment]
@Baltoli I seem to remember we discussed this and I suggested some sort of a fix, but didn't put anything down on this issue. Is this still relevant/does this need addressing?

**Comment by Baltoli** [comment]
Feel free to close; as I recall there wasn't a satisfactory way to avoid this other than stack caching. Thanks though!
