### ISSUE TITLE
Suspected configuration blow-up in `evm-semantics/tests/specs/benchmarks/ecrecover00-siginvalid-spec.k`

### ISSUE THREAD

**Issue by geo2a** [runtimeverification/hs-backend-booster#347]
The recent CI runs in `evm-semantics` were suffering from `kore-rpc-booster` consuming too much memory when proving `evm-semantics/tests/specs/benchmarks/ecrecover00-siginvalid-spec.k`. The issue has been mitigating by limiting rewriting depth to 300. This is symptomatic of the problem highlighted in https://github.com/runtimeverification/hs-backend-booster/issues/331. We need to profile `ecrecover00-siginvalid-spec.k` to confirm that it is the same issue.

**Comment by jberthold** [comment]
A request file and (Haskell) definition for `ecrecover00-siginvalid`  are attached here. Symptom is that the server memory grows considerably when running more than ~300 steps (remarkable growth around 360-370). When running the 300 steps and then making a new request with the resulting state, the memory does _not_ (immediately) grow.



[exec-request-after300.json](https://github.com/runtimeverification/hs-backend-booster/files/13164473/exec-request-after300.json)
[exec-request365.json](https://github.com/runtimeverification/hs-backend-booster/files/13164472/exec-request365.json)

**Comment by geo2a** [comment]
The regression has been introduced by https://github.com/runtimeverification/hs-backend-booster/pull/333 and is fixed by reverting the change (PR https://github.com/runtimeverification/hs-backend-booster/pull/348)
