### ISSUE TITLE
Simplification of `==K` in the booster

### ISSUE THREAD

**Issue by goodlyrottenapple** [runtimeverification/hs-backend-booster#367]
As @virgil-serbanuta pointed out in a recent discussion, the booster currently cannot reason over `==K` terms containing variables. I believe in the old backend, we use the following rule:

```
rule {K1 ==K K2 #Equals true} => {K1 #Equals K2} [simplification]
```
and then use reasoning over `#Equals`, which is built into the old backend. 

Ideally, the front-end should generate equations for `==K` for any given sort, corresponding to structural equality/structural equality+AC (I presume?? It's not even clear what `==K` is, given there are no equations for it as it is hooked in one way or the other in both back-ends) instead of relying on built-ins, as this makes things a lot more scrutable.

Obviously, a simpler alternative would be to just implement a custom simplifier in the booster and call it whenever we see `==K`, to deal with instances such as `CONSTR1( ... VarX ...) ==K CONSTR2(...)` which cannot be sent to the llvm backend but can easily be discharged as false, given `CONSTR1 /= CONSTR2`

**Comment by goodlyrottenapple** [comment]
corresponding issue in K https://github.com/runtimeverification/k/issues/3810

**Comment by ehildenb** [comment]
I think generating axioms in the frontend should be easy enough for free constructors, and that would allow the booster to make more progress.

**Comment by virgil-serbanuta** [comment]
Here is a bug report for a minimized semantics, I can also provide one for the entire semantics:
[bug-report.tar.gz](https://github.com/runtimeverification/hs-backend-booster/files/13367867/bug-report.tar.gz)
