### ISSUE TITLE
Updating HB to a non-master branch produces Nix error

### ISSUE THREAD

**Issue by geo2a** [runtimeverification/hs-backend-booster#372]
I've made a change to HB and wanted to check it in Booster's CI, so I ran `./scripts/update-haskell-backend.sh BRANCH`, committed and pushed. The CI fails with:  

```
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'ghc-shell-for-hs-backend-booster-0.0.0-0'
         whose name attribute is located at /nix/store/mbz4hixfgxq5b6vc0k3pp2iglcd4c353-source/pkgs/stdenv/generic/make-derivation.nix:303:7

       … while evaluating attribute 'NIX_GHC' of derivation 'ghc-shell-for-hs-backend-booster-0.0.0-0'

         at /nix/store/mbz4hixfgxq5b6vc0k3pp2iglcd4c353-source/pkgs/development/haskell-modules/generic-builder.nix:676:9:

          675|         LOCALE_ARCHIVE = lib.optionalString (stdenv.hostPlatform.libc == "glibc") "${buildPackages.glibcLocales}/lib/locale/locale-archive";
          676|         "NIX_${ghcCommandCaps}" = "${ghcEnv}/bin/${ghcCommand}";
             |         ^
          677|         "NIX_${ghcCommandCaps}PKG" = "${ghcEnv}/bin/${ghcCommand}-pkg";

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: Cannot find Git revision '59b5b34de1119d3da2d3b9cc2a4ffd2abbddb571' in ref 'refs/heads/master' of repository 'https://github.com/runtimeverification/haskell-backend.git'! Please make sure that the rev exists on the ref you've specified or add allRefs = true; to fetchGit.
```

The relevant part seems to be at the end: `Cannot find Git revision '59b5b34de1119d3da2d3b9cc2a4ffd2abbddb571' in ref 'refs/heads/master' of repository 'https://github.com/runtimeverification/haskell-backend.git'! Please make sure that the rev exists on the ref you've specified or add allRefs = true; to fetchGit`. Here's the [CI run](https://github.com/runtimeverification/hs-backend-booster/actions/runs/6888376727/job/18737261449?pr=371). 

I have not running `nix build` locally, but I did try `kup install kontrol --override BOOSTER BRANCH`, and that gives the same error.

Perhaps we need to give some more parameters to `stacklock2nix`? Or modify the lock file itself in a different way?

**Comment by goodlyrottenapple** [comment]
Here is the issue in stacklock2nix: https://github.com/cdepillabout/stacklock2nix/issues/38

**Comment by geo2a** [comment]
`stacklock2nix` has been update and the workaround has been reverted: https://github.com/runtimeverification/hs-backend-booster/pull/407
