### ISSUE TITLE
Discussion on refactoring

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/hs-backend-booster#41]
Also see TODO list in https://github.com/runtimeverification/hs-backend-booster/pull/22

**Comment by goodlyrottenapple** [comment]
I don't think we need to do a major refactor, as we seem to have coalesced on a pretty sensible structure. The only point in the module hierarchy I always struggle to find is the internalisation of modules/patterns from kore. One suggestion I have for a minor tweak to the modules would be to flatten the syntax module from `Syntax.ParsedKore` to just `TextualKore` and `Syntax.Json` to `KoreJson`.
