### ISSUE TITLE
Return the actual branch condition from backend

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/hs-backend-booster#413]
Currently, when we get a `branch` result back from the backend, we get back:

- `pre-branch-state`: state before the branch.
- `post-branch-states`: states after the branch.

Then pyk looks at these states, and tries to infer what the branching condition was which led to the branch [code here](https://github.com/runtimeverification/pyk/blob/3797a9eb170d6255502eaccea2d50a4c63e4f705/src/pyk/kcfg/explore.py#L430). It does this by trying to find new unique conditions in each branch that are obviously mutially exclusive, but this will only work if the conditions added are of the form `B` and on the other branch `notBool B`.

There are several cases where the conditions don't look like that, for example:

- On one branch, we _unify_ a variable like `CALLVALUE` with a concrete value like `0`. Then on on branch, we have no new conditions (the new substitution is applied directly), and on the other branch, we hav a new condition like `notBool CALLVALUE ==K 0`. This is a branch happening at unification time.
- We have a branch condition that is more than 2-way (3 rules could apply, with different branch conditions).

Because of this, we also end up calling the `execute` endpoint _twice_ for each branch, to confirm that it's a branch, which is a waste of time in the pyk code.

The backend could return, on `Branch` responses, and _optional_ field `branch_conditions`, with the following properties:

- They are _complete_: the union of all th ebranch conditions is `#Top`, for example `{ true #Equals 0 ==K CALLVALUE }` and `{ false #Equals 0 ==K CALLVALUE }` are complete.
- They are _mutually exclusive_: no overlap betwene them.
- Each condition returned, when applied to the pre-state, only results in _one_ of the branches being taken.
- They contain information about _both_ unification and side-condition evaluation. So for each branch, the condition that is returned is the unifier (in the form of `{ VAR #Equals TERM } #And { ... }`, or a more structured substitution), _and_ any side-conditions that had to evaluate to true (in the form of `{ true #Equals PRED }`).

If this extra information is missing, we can fallback to the original logic in pyk, if it's there, we can use this faster routine for inferring it (and avoid `NDBranch` being inserted in many cases).

We could potentially use the existing `substitution` and `predicate` fields for this, but I think it's better to make a new field called `conditions: [ { "unifier": UNIFIER1, "side-condition": SIDE_CONDITION_1 } , ... { "unifier": UNIFIER_N, "side-condition": SIDE_CONDITION_N } ]` that is _optional_, so that we don't have to update `kore` backend, can just implement it in the booster and use it opportunistically in pyk when the data is available. Then when the booster sees a branch, it can first check with the old backend that it _actually_ is a branch, and if it is, include this extra information in the overall response (only enable collecting this information in the booster).

**Comment by tothtamas28** [comment]
In order to avoid losing branch conditions, a case to consider: branching so that all next-states except one simplify to `#Bottom`.
