### ISSUE TITLE
Implement `hook(MAP.in_keys)`

### ISSUE THREAD

**Issue by geo2a** [runtimeverification/hs-backend-booster#422]
In a recent bug report we've seen Booster aborting on a condition of form:
```
notBool (concrete_int_N in_keys {concrete_int_1 -> concrete_value1, ..., concrete_int_N -> SYMBOLIC_VALUE, ... })
```
i.e. negation of a map membership where everything is concrete but one value (not key) in the map.

Booster has long been offloading hooks to the LLVM backend, but here we cannot quite do it because one of the values is symbolic (even though `in_keys` should not in principle need to care about values).

**Comment by jberthold** [comment]
Not adding the hook at this point, as there is a better solution for the problem it was trying to solve
