### ISSUE TITLE
Unexpected sort after LLVM simplification

### ISSUE THREAD

**Issue by virgil-serbanuta** [runtimeverification/hs-backend-booster#449]
When running the adder property with Kasmer, the debug output contains several long lines that start with `Unexpected sort after LLVM simplification`, e.g.:

```
[Error] Unexpected sort after LLVM simplification: Term (TermAttributes {variables = fromList [], isEvaluated = True, hash = -301300784551631014, isConstructorLike = True, canBeEvaluated = True}) (DomainValueF (SortApp "SortWasmStringToken" []) "\"add\"") Expected sort SortApp "SortWasmString" []
```

Here is a bug report that should help reproducing this:
[booster-llvm.tar.gz](https://github.com/runtimeverification/hs-backend-booster/files/13876927/booster-llvm.tar.gz)

**Comment by virgil-serbanuta** [comment]
$ kore-rpc-booster --version
hs-backend-booster version:
  revision:     445bc0723dd7ae2584e3b794a6b8bd3cadef0ce1
  branch:       HEAD
  last commit:  Thu Dec 21 10:36:52 2023 +0100

**Comment by jberthold** [comment]
It would be good to also know the version of K (and specifically, the LLVM backend used by that version of K)
(we added a new code path in late December to prepare for a change in the LLVM backend's simplify API).

**Comment by jberthold** [comment]
From code inspection: it appears that the LLVM backend returns this wrong sort, and the code path that is taken is the old (workaround) that got removed 2 days ago.
We need to re-test this with the latest versions of LLVM-backend (meaning latest K) and booster to decide the right fix

**Comment by jberthold** [comment]
@virgil-serbanuta Is this issue still reproducible with the latest versions of K, LLVM-backend, and Booster?
Your [post on slack](https://runtimeverification.slack.com/archives/CC360GUTG/p1705353571426959?thread_ts=1705005527.808069&cid=CC360GUTG) seems to suggest that this is now working for you, please advise whether we can close the issue.

**Comment by virgil-serbanuta** [comment]
I am running some tests at the moment, and I would prefer to not upgrade my K version until they finish. Unless you say otherwise, I'll test this tomorrow or the day after.

**Comment by geo2a** [comment]
@virgil-serbanuta we're closing the issue as fixed, please reopen as necessary.

**Comment by virgil-serbanuta** [comment]
This seems to work properly now, thank you!
