### ISSUE TITLE
Warn when loading library and mutable bytes are enabled

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/hs-backend-booster#490]
If `kllvm_mutable_bytes_enabled()` returns `true`, emit ~~an error~~ a warning on loading the C library.

**Comment by jberthold** [comment]
Clarification: "emit an error" should be visible to the user but not immediately aborting the server execution?
(this is what we will implement for the moment)

**Comment by Baltoli** [comment]
Yep - typed this up too quickly! It definitely shouldn't be a fatal error, but rather just a warning. We should permit users who are happy to assert that their specific semantics doesn't trigger the unsound behaviour (e.g. the C semantics) to carry on executing.
