### ISSUE TITLE
Return additional branching information from kore-rpc-booster

### ISSUE THREAD

**Issue by jberthold** [runtimeverification/hs-backend-booster#499]
#496 updates haskell-backend to a version that includes additional information in `Branching` responses. 
`kore-rpc-booster` should return the same additional information

(This will require modifications to a number of integration tests. Possibly the best solution is to re-create the foundry tarball regression test with the current versions of K, llvm-backend, and updated booster).

**Comment by goodlyrottenapple** [comment]
closing in favour of #536
