### ISSUE TITLE
Booster is slow on some tests in `pyk`

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/hs-backend-booster#569]
Related:
* runtimeverification/pyk#1058

The tests are for the `IMP` semantics, so it would make sense if the Booster simplification had a significant overhead due to the small configuration. Nevertheless, it might be worth looking into.

```
$ make test-integration TEST_ARGS='-k TestImpProof'
...
====================================================================== slowest durations =======================================================================
102.19s call     src/tests/integration/proof/test_imp.py::TestImpProof::test_all_path_reachability_prove[booster-imp-simple-sum-100]
55.71s call     src/tests/integration/proof/test_imp.py::TestImpProof::test_all_path_bmc_reachability_prove[booster-bmc-two-loops-symbolic-2]
50.09s call     src/tests/integration/proof/test_imp.py::TestImpProof::test_fail_fast[booster]
34.98s call     src/tests/integration/proof/test_imp.py::TestImpProof::test_all_path_bmc_reachability_prove[booster-bmc-loop-symbolic-3]
31.58s call     src/tests/integration/proof/test_imp.py::TestImpProof::test_failure_info[booster-fail-fast]
27.01s call     src/tests/integration/proof/test_imp.py::TestImpProof::test_all_path_reachability_prove[booster-imp-simple-sum-loop]
25.86s call     src/tests/integration/proof/test_imp.py::TestImpProof::test_all_path_bmc_reachability_prove[booster-bmc-loop-symbolic-2]
25.00s call     src/tests/integration/proof/test_imp.py::TestImpProof::test_failure_info_recomputed_on_proof_reinit[booster-failing-if]
24.02s call     src/tests/integration/proof/test_imp.py::TestImpProof::test_all_path_reachability_prove[booster-imp-if-almost-same-times]
23.79s call     src/tests/integration/proof/test_imp.py::TestImpProof::test_failure_info[booster-fail-branch]
23.25s call     src/tests/integration/proof/test_imp.py::TestImpProof::test_failure_info_recomputed_on_proof_reinit[booster-fail-branch]
21.80s call     src/tests/integration/proof/test_imp.py::TestImpProof::test_all_path_reachability_prove[booster-imp-if-almost-same-plus]
20.70s call     src/tests/integration/proof/test_imp.py::TestImpProof::test_all_path_reachability_prove[booster-imp-simple-sum-10]
19.68s call     src/tests/integration/proof/test_imp.py::TestImpProof::test_failure_info[booster-failing-if]
18.57s call     src/tests/integration/proof/test_imp.py::TestImpProof::test_all_path_bmc_reachability_prove[booster-bmc-two-loops-symbolic-1]
17.74s call     src/tests/integration/proof/test_imp.py::TestImpProof::test_all_path_bmc_reachability_prove[legacy-bmc-two-loops-symbolic-2]
14.42s call     src/tests/integration/proof/test_imp.py::TestImpProof::test_all_path_bmc_reachability_prove[booster-bmc-loop-concrete-3]
14.31s call     src/tests/integration/proof/test_imp.py::TestImpProof::test_all_path_bmc_reachability_prove[booster-bmc-loop-symbolic-1]
14.20s call     src/tests/integration/proof/test_imp.py::TestImpProof::test_fail_fast[legacy]
...
```

**Comment by ehildenb** [comment]
Are they specifically _slower_ than the old backend?

**Comment by tothtamas28** [comment]
> Are they specifically _slower_ than the old backend?

Yes. The list above is ascending in execution time, and for each test there is a run `booster` and `legacy`. For example:

```
50.09s call     src/tests/integration/proof/test_imp.py::TestImpProof::test_fail_fast[booster]
...
14.20s call     src/tests/integration/proof/test_imp.py::TestImpProof::test_fail_fast[legacy]
```

**Comment by jberthold** [comment]
The first thing to check would be whether the llvm-backend library is used in these tests. Otherwise booster will fall back about every step to do the necessary arithmetic (and there is not much else to do for an `IMP` program).
Once that question is answered, we can look into what exactly is happening and where the overhead might be.

**Comment by tothtamas28** [comment]
> The first thing to check would be whether the llvm-backend library is used in these tests

You mean check the logs for fallbacks?

**Comment by jberthold** [comment]
> > The first thing to check would be whether the llvm-backend library is used in these tests
> 
> You mean check the logs for fallbacks?

I mean check that we build the llvm shared library interpreter and  use it with the `llvm-backend-library` flag for `booster` when the tests are run. You would see that very quickly in the logs by way of the unification failing more often than not.

**Comment by jberthold** [comment]
We have an integration test using an `IMP` language to compute `\sum_1^{10000} n` and it [usually finishes in around 30 sec](https://github.com/runtimeverification/hs-backend-booster/actions/runs/8552650715/job/23434200990#step:8:21735).
Which is not super-fast either... but no fallbacks at all.
Maybe worth considering to make changes to the `IMP` definition to align with our version - the way the `Map` lookups  are encoded might break its back in the `pyk` version. See [here for our `IMP` version](https://github.com/runtimeverification/hs-backend-booster/blob/1e4cc4908db9578735218b2cb69164dd43a1e0b5/test/rpc-integration/resources/imp.k).

**Comment by tothtamas28** [comment]
> Maybe worth considering to make changes to the `IMP` definition to align with our version

Awesome, I will try the tests with this version then.

> I mean check that we build the llvm shared library interpreter and use it with the `llvm-backend-library` flag for `booster`

Pyk treats that parameter as required, so I don't think that's the issue. But if the changes to the definition do not solve the issue then I'll look into this more closely.

**Comment by tothtamas28** [comment]
Opened a PR with the `#lookup`-based `IMP`:
* runtimeverification/pyk#1063

**Comment by jberthold** [comment]
I believe this issue can be closed now... please re-open otherwise
